// demos/react/src/sections/FetchDemo.tsx
import { useState } from 'react'
import { useErrorEngine } from 'gracefulerrors/react'
import { createFetch } from 'gracefulerrors'

export default function FetchDemo() {
  const engine = useErrorEngine()
  const [log, setLog] = useState<Array<{ label: string; url: string; mode: string; outcome: string }>>([])

  const addLog = (label: string, url: string, mode: string, outcome: string) => {
    setLog(prev => [{ label, url, mode, outcome }, ...prev.slice(0, 4)])
  }

  const runFetch = async (url: string, mode: 'throw' | 'handle' | 'silent', label: string) => {
    if (!engine) return
    const fetchWrapper = createFetch(engine, { mode })
    try {
      const res = await fetchWrapper(url)
      addLog(label, url, mode, res ? `OK ${res.status}` : 'undefined (error handled)')
    } catch (e) {
      addLog(label, url, mode, `thrown: ${e instanceof Response ? `Response(${e.status})` : String(e)}`)
    }
  }

  return (
    <div className="p-6">
      <div className="mb-5">
        <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-lime-600 bg-lime-50 border border-lime-200 px-2.5 py-0.5 rounded-full mb-2">
          createFetch
        </span>
        <h2 className="text-xl font-bold text-slate-900">createFetch Wrapper</h2>
        <p className="text-slate-500 text-sm mt-1">
          <code className="bg-slate-100 text-slate-700 px-1 rounded text-xs">createFetch(engine, {'{ mode }'})</code>{' '}
          wraps the native <code className="bg-slate-100 text-slate-700 px-1 rounded text-xs">fetch</code> and
          automatically forwards HTTP errors to the engine. Three modes control behavior after engine.handle():
        </p>
        <ul className="mt-2 text-sm text-slate-500 space-y-0.5 list-disc list-inside">
          <li><strong>throw</strong> — calls engine.handle(), then re-throws</li>
          <li><strong>handle</strong> — calls engine.handle(), returns undefined</li>
          <li><strong>silent</strong> — returns the raw Response, does not call engine.handle()</li>
        </ul>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-5 text-xs">
        {(['throw', 'handle', 'silent'] as const).map(mode => (
          <div
            key={mode}
            className="border border-slate-200 rounded-lg p-3 bg-white"
          >
            <p className="font-semibold text-slate-700 mb-2 capitalize">Mode: {mode}</p>
            <div className="space-y-2">
              <button
                onClick={() => runFetch('https://httpstat.us/404', mode, `404 (${mode})`)}
                className="w-full bg-amber-500 hover:bg-amber-600 text-white text-xs px-3 py-1.5 rounded-lg font-medium transition-colors"
              >
                GET /404
              </button>
              <button
                onClick={() => runFetch('https://httpstat.us/500', mode, `500 (${mode})`)}
                className="w-full bg-red-500 hover:bg-red-600 text-white text-xs px-3 py-1.5 rounded-lg font-medium transition-colors"
              >
                GET /500
              </button>
              <button
                onClick={() => runFetch('https://httpstat.us/200', mode, `200 (${mode})`)}
                className="w-full bg-emerald-500 hover:bg-emerald-600 text-white text-xs px-3 py-1.5 rounded-lg font-medium transition-colors"
              >
                GET /200 (success)
              </button>
            </div>
          </div>
        ))}
      </div>

      {log.length > 0 && (
        <div className="overflow-x-auto mb-4">
          <table className="w-full text-xs border-collapse">
            <thead>
              <tr className="bg-slate-100">
                <th className="text-left px-3 py-2 font-semibold text-slate-600">Request</th>
                <th className="text-left px-3 py-2 font-semibold text-slate-600">Mode</th>
                <th className="text-left px-3 py-2 font-semibold text-slate-600">Outcome</th>
              </tr>
            </thead>
            <tbody>
              {log.map((entry, i) => (
                <tr key={i} className="border-t border-slate-200">
                  <td className="px-3 py-2 font-mono text-slate-700">{entry.label}</td>
                  <td className="px-3 py-2">
                    <span className={`inline-flex px-1.5 py-0.5 rounded text-xs font-mono font-medium ${
                      entry.mode === 'throw' ? 'bg-red-100 text-red-700' :
                      entry.mode === 'handle' ? 'bg-sky-100 text-sky-700' :
                      'bg-slate-100 text-slate-700'
                    }`}>
                      {entry.mode}
                    </span>
                  </td>
                  <td className="px-3 py-2 font-mono text-slate-600">{entry.outcome}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg text-xs text-amber-800">
        Note: These requests hit <code className="font-mono">httpstat.us</code> which returns mock HTTP status codes.
        If the request fails due to CORS or network issues, the error is still forwarded to the engine.
      </div>

      <div className="mt-3 p-3 bg-slate-50 rounded-lg border border-slate-200 text-xs text-slate-500 font-mono">
        const fetchWithEngine = createFetch(engine, {'{ mode: "handle" }'})<br />
        await fetchWithEngine('/api/resource')<br />
        <span className="text-slate-400">// 4xx/5xx → engine.handle() called automatically</span>
      </div>
    </div>
  )
}

// demos/vue/src/sections/FetchDemo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { createFetch } from 'gracefulerrors'
import { engine } from '../engine'

const fetchHandle = createFetch(engine, { mode: 'handle' })
const fetchThrow = createFetch(engine, { mode: 'throw' })
const fetchSilent = createFetch(engine, { mode: 'silent' })

const log = ref<Array<{ id: number; url: string; mode: string; result: string; color: string }>>([])
let ctr = 0

async function tryFetch(
  fn: ReturnType<typeof createFetch>,
  url: string,
  mode: string
) {
  try {
    const res = await fn(url)
    if (res) {
      log.value.unshift({ id: ++ctr, url, mode, result: `OK ${res.status}`, color: 'var(--accent-green)' })
    } else {
      log.value.unshift({ id: ++ctr, url, mode, result: 'undefined (handled by engine)', color: 'var(--accent-yellow)' })
    }
  } catch (e) {
    log.value.unshift({ id: ++ctr, url, mode, result: `THROWN: ${e instanceof Error ? e.message : String(e)}`, color: 'var(--accent-red)' })
  }
  if (log.value.length > 10) log.value.pop()
}
</script>

<template>
  <div class="card" style="padding: 20px;">
    <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 6px;">
      <div class="accent-line" style="background: var(--accent-blue);" />
      <h2 class="section-title">createFetch Wrapper</h2>
      <span class="badge badge-blue">createFetch</span>
    </div>
    <p style="color: var(--text-dim); font-size: 12px; margin: 0 0 16px; line-height: 1.6;">
      <code style="color: var(--accent-cyan); font-size: 11px;">createFetch(engine, { mode })</code> wraps native <code style="color: var(--accent-cyan); font-size: 11px;">fetch</code>.
      On non-OK responses, it automatically routes errors through the engine.
      Three modes: <code style="color: var(--accent-green); font-size: 11px;">'handle'</code> (engine handles, returns undefined),
      <code style="color: var(--accent-red); font-size: 11px;">'throw'</code> (re-throws after handling),
      <code style="color: var(--text-dim); font-size: 11px;">'silent'</code> (engine skipped, throw through).
    </p>

    <div style="display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px;">
      <!-- mode: handle -->
      <button class="btn btn-success" @click="tryFetch(fetchHandle, 'https://httpbin.org/get', 'handle')">
        200 OK (handle)
      </button>
      <button class="btn btn-danger" @click="tryFetch(fetchHandle, 'https://httpbin.org/status/404', 'handle')">
        404 — mode: handle
      </button>
      <button class="btn btn-danger" @click="tryFetch(fetchHandle, 'https://httpbin.org/status/500', 'handle')">
        500 — mode: handle
      </button>
      <button class="btn btn-warning" @click="tryFetch(fetchThrow, 'https://httpbin.org/status/401', 'throw')">
        401 — mode: throw
      </button>
      <button class="btn btn-ghost" @click="tryFetch(fetchSilent, 'https://httpbin.org/status/400', 'silent')">
        400 — mode: silent
      </button>
      <button class="btn btn-ghost" @click="tryFetch(fetchHandle, 'https://this-domain-does-not-exist-xyz.com', 'handle')">
        Network failure (handle)
      </button>
    </div>

    <div v-if="log.length">
      <div class="code-block" style="font-size: 11px;">
        <div v-for="row in log" :key="row.id" style="padding: 4px 0; border-bottom: 1px solid #1e1e35; display: grid; grid-template-columns: 20px 80px 180px 1fr; gap: 8px; align-items: center;">
          <span style="color: var(--text-muted);">{{ row.id }}</span>
          <span style="color: var(--accent-purple);">{{ row.mode }}</span>
          <span style="color: var(--text-dim); overflow: hidden; text-overflow: ellipsis; white-space: nowrap;" :title="row.url">{{ row.url.replace('https://', '') }}</span>
          <span :style="{ color: row.color }">{{ row.result }}</span>
        </div>
      </div>
    </div>
    <div v-else style="color: var(--text-muted); font-size: 11px; padding: 12px 0;">
      Click a button to fire a fetch request. Errors route through the engine automatically.
    </div>

    <div style="margin-top: 14px;" class="code-block">const fetch = createFetch(engine, { mode: 'handle' })
// Non-OK response → engine.handle(payload) → returns undefined</div>
  </div>
</template>
