// demos/react/src/sections/InlineDemo.tsx
import { useState } from 'react'
import { useErrorEngine } from 'gracefulerrors/react'
import { useFieldError } from 'gracefulerrors/react'

function FieldInput({
  label,
  field,
  type = 'text',
  placeholder,
}: {
  label: string
  field: string
  type?: string
  placeholder?: string
}) {
  const { error } = useFieldError(field)
  return (
    <div className="flex flex-col gap-1">
      <label className="text-sm font-medium text-slate-700">{label}</label>
      <input
        type={type}
        placeholder={placeholder}
        className={`border rounded-lg px-3 py-2 text-sm outline-none transition-all ${
          error
            ? 'border-red-400 bg-red-50 focus:ring-2 focus:ring-red-300'
            : 'border-slate-300 focus:border-sky-500 focus:ring-2 focus:ring-sky-200'
        }`}
      />
      {error && (
        <p className="text-xs text-red-600 flex items-center gap-1 animate-pulse">
          <span>⚠</span> {error.message}
        </p>
      )}
    </div>
  )
}

export default function InlineDemo() {
  const engine = useErrorEngine()
  const [submitted, setSubmitted] = useState(false)

  const triggerValidation = () => {
    setSubmitted(true)
    engine?.handle({ code: 'FORM_EMAIL_INVALID', context: { field: 'email' } })
    engine?.handle({ code: 'FORM_PASSWORD_TOO_SHORT', context: { field: 'password' } })
    engine?.handle({ code: 'FORM_REQUIRED', context: { field: 'username' } })
  }

  const triggerSingle = (field: string, code: string) => {
    engine?.handle({ code, context: { field } })
  }

  const clearField = (code: string) => {
    engine?.clear(code as Parameters<typeof engine.clear>[0])
  }

  return (
    <div className="p-6">
      <div className="mb-5">
        <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-600 bg-emerald-50 border border-emerald-200 px-2.5 py-0.5 rounded-full mb-2">
          ui: 'inline'
        </span>
        <h2 className="text-xl font-bold text-slate-900">Inline Field Errors</h2>
        <p className="text-slate-500 text-sm mt-1">
          <code className="bg-slate-100 text-slate-700 px-1 rounded text-xs">useFieldError(field)</code>{' '}
          subscribes to inline errors for a specific field. The engine routes errors with{' '}
          <code className="bg-slate-100 text-slate-700 px-1 rounded text-xs">context.field</code> to the
          matching hook automatically.
        </p>
      </div>

      <div className="max-w-sm space-y-4">
        <FieldInput label="Username" field="username" placeholder="Enter username" />
        <FieldInput label="Email" field="email" type="email" placeholder="you@example.com" />
        <FieldInput label="Password" field="password" type="password" placeholder="••••••••" />
      </div>

      <div className="mt-5 flex flex-wrap gap-2">
        <button
          onClick={triggerValidation}
          className="bg-emerald-600 hover:bg-emerald-700 text-white text-sm px-4 py-2 rounded-lg font-medium transition-colors"
        >
          Simulate Form Validation (all fields)
        </button>
        <button
          onClick={() => triggerSingle('email', 'FORM_EMAIL_INVALID')}
          className="bg-slate-700 hover:bg-slate-800 text-white text-sm px-4 py-2 rounded-lg font-medium transition-colors"
        >
          Email error only
        </button>
        <button
          onClick={() => triggerSingle('password', 'FORM_PASSWORD_TOO_SHORT')}
          className="bg-slate-700 hover:bg-slate-800 text-white text-sm px-4 py-2 rounded-lg font-medium transition-colors"
        >
          Password error only
        </button>
        {submitted && (
          <button
            onClick={() => {
              clearField('FORM_EMAIL_INVALID')
              clearField('FORM_PASSWORD_TOO_SHORT')
              clearField('FORM_REQUIRED')
              setSubmitted(false)
            }}
            className="bg-white hover:bg-slate-50 text-slate-700 text-sm px-4 py-2 rounded-lg font-medium border border-slate-300 transition-colors"
          >
            Clear all field errors
          </button>
        )}
      </div>

      <div className="mt-4 p-3 bg-slate-50 rounded-lg border border-slate-200 text-xs text-slate-500 font-mono">
        <span className="text-slate-400">// In your component:</span><br />
        const {'{ error }'} = useFieldError('email')<br />
        <span className="text-slate-400">// Trigger:</span><br />
        engine.handle({'{ code: "FORM_EMAIL_INVALID", context: { field: "email" } }'})
      </div>
    </div>
  )
}

// demos/vue/src/sections/InlineDemo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useFieldError } from 'gracefulerrors/vue'
import { engine } from '../engine'

const email = ref('')
const password = ref('')
const name = ref('')

const { error: emailError } = useFieldError('email')
const { error: passwordError } = useFieldError('password')
const { error: nameError } = useFieldError('name')

function triggerEmailError() {
  engine.handle({ code: 'FORM_VALIDATION_EMAIL', context: { field: 'email' } })
}
function triggerPasswordError() {
  engine.handle({ code: 'FORM_VALIDATION_MIN_LENGTH', context: { field: 'password', min: 12 } })
}
function triggerNameError() {
  engine.handle({ code: 'FORM_VALIDATION_REQUIRED', context: { field: 'name' } })
}
function clearAll() {
  engine.clearAll()
  email.value = ''
  password.value = ''
  name.value = ''
}

function handleSubmit() {
  engine.clearAll()
  let hasError = false
  if (!email.value || !email.value.includes('@')) {
    engine.handle({ code: 'FORM_VALIDATION_EMAIL', context: { field: 'email' } })
    hasError = true
  }
  if (!password.value || password.value.length < 8) {
    engine.handle({ code: 'FORM_VALIDATION_MIN_LENGTH', context: { field: 'password', min: 8 } })
    hasError = true
  }
  if (!name.value.trim()) {
    engine.handle({ code: 'FORM_VALIDATION_REQUIRED', context: { field: 'name' } })
    hasError = true
  }
  if (!hasError) {
    engine.handle({ code: 'ORDER_FAILED' })
  }
}
</script>

<template>
  <div class="card" style="padding: 20px;">
    <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 6px;">
      <div class="accent-line" style="background: var(--accent-cyan);" />
      <h2 class="section-title">Inline Field Errors</h2>
      <span class="badge badge-cyan">ui: 'inline'</span>
    </div>
    <p style="color: var(--text-dim); font-size: 12px; margin: 0 0 16px; line-height: 1.6;">
      <code style="color: var(--accent-cyan); font-size: 11px;">useFieldError(field)</code> subscribes to inline errors for a specific field.
      Errors routed as <code style="color: var(--accent-cyan); font-size: 11px;">'inline'</code> with a matching <code style="color: var(--accent-cyan); font-size: 11px;">context.field</code> are surfaced reactively.
    </p>

    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; max-width: 600px;">
      <!-- Name -->
      <div style="grid-column: 1 / -1;">
        <label style="display: block; font-size: 11px; color: var(--text-dim); margin-bottom: 5px; letter-spacing: 0.04em;">
          FULL NAME
        </label>
        <input
          v-model="name"
          class="input"
          :class="{ 'error-field': nameError }"
          placeholder="Your name..."
        />
        <div v-if="nameError" style="margin-top: 4px; font-size: 11px; color: var(--accent-red); display: flex; align-items: center; gap: 4px;">
          <span>⊗</span> {{ nameError.message }}
        </div>
      </div>

      <!-- Email -->
      <div>
        <label style="display: block; font-size: 11px; color: var(--text-dim); margin-bottom: 5px; letter-spacing: 0.04em;">
          EMAIL
        </label>
        <input
          v-model="email"
          class="input"
          :class="{ 'error-field': emailError }"
          placeholder="user@example.com"
          type="email"
        />
        <div v-if="emailError" style="margin-top: 4px; font-size: 11px; color: var(--accent-red); display: flex; align-items: center; gap: 4px;">
          <span>⊗</span> {{ emailError.message }}
        </div>
      </div>

      <!-- Password -->
      <div>
        <label style="display: block; font-size: 11px; color: var(--text-dim); margin-bottom: 5px; letter-spacing: 0.04em;">
          PASSWORD
        </label>
        <input
          v-model="password"
          class="input"
          :class="{ 'error-field': passwordError }"
          placeholder="Min 8 chars..."
          type="password"
        />
        <div v-if="passwordError" style="margin-top: 4px; font-size: 11px; color: var(--accent-red); display: flex; align-items: center; gap: 4px;">
          <span>⊗</span> {{ passwordError.message }}
        </div>
      </div>
    </div>

    <div style="display: flex; flex-wrap: wrap; gap: 8px; margin-top: 16px;">
      <button class="btn btn-primary" @click="handleSubmit">Submit form (validates all)</button>
      <button class="btn btn-danger" @click="triggerEmailError">Email error only</button>
      <button class="btn btn-warning" @click="triggerPasswordError">Password error only</button>
      <button class="btn btn-ghost" @click="triggerNameError">Name required error</button>
      <button class="btn btn-ghost" @click="clearAll">Clear all</button>
    </div>

    <div style="margin-top: 14px;" class="code-block">const { error } = useFieldError('email')
// error.value → AppError | null</div>
  </div>
</template>
