// demos/react/src/App.tsx
import { useState, useEffect } from 'react'
import { ErrorEngineProvider } from 'gracefulerrors/react'
import { SonnerToaster } from 'gracefulerrors/sonner'
import { engine, lifecycleLogs, logSubscribers, type LogEntry } from './engine'

import ToastDemo from './sections/ToastDemo'
import ModalDemo from './sections/ModalDemo'
import InlineDemo from './sections/InlineDemo'
import SilentDemo from './sections/SilentDemo'
import FallbackDemo from './sections/FallbackDemo'
import DedupeDemo from './sections/DedupeDemo'
import MaxConcurrentDemo from './sections/MaxConcurrentDemo'
import TransformDemo from './sections/TransformDemo'
import NormalizerDemo from './sections/NormalizerDemo'
import FetchDemo from './sections/FetchDemo'
import BoundaryDemo from './sections/BoundaryDemo'
import CallbacksDemo from './sections/CallbacksDemo'
import DebugDemo from './sections/DebugDemo'

// ---------------------------------------------------------------------------
// Log type colors
// ---------------------------------------------------------------------------
const LOG_COLORS: Record<string, string> = {
  onError:       'text-red-400',
  onNormalized:  'text-yellow-300',
  onRouted:      'text-green-400',
  onSuppressed:  'text-purple-400',
  onFallback:    'text-orange-400',
  onDropped:     'text-red-500',
  ERROR_ADDED:   'text-sky-400',
  ERROR_CLEARED: 'text-slate-400',
  ALL_CLEARED:   'text-slate-500',
}

function LogBadge({ type }: { type: string }) {
  const color = LOG_COLORS[type] ?? 'text-slate-400'
  return (
    <span className={`font-mono text-xs font-semibold ${color}`}>{type}</span>
  )
}

function LogPanel({ logs }: { logs: LogEntry[] }) {
  return (
    <aside className="w-80 min-w-[280px] bg-slate-900 border-l border-slate-700 flex flex-col h-screen sticky top-0">
      <div className="px-4 py-3 border-b border-slate-700 flex items-center justify-between">
        <div>
          <h2 className="text-white font-semibold text-sm tracking-wide">Live Event Log</h2>
          <p className="text-slate-400 text-xs mt-0.5">engine.subscribe() + lifecycle hooks</p>
        </div>
        <button
          onClick={() => engine.clearAll()}
          className="text-xs text-slate-400 hover:text-white bg-slate-800 hover:bg-slate-700 px-2 py-1 rounded transition-colors"
        >
          Clear all
        </button>
      </div>
      <div className="flex-1 overflow-y-auto px-3 py-2 space-y-1">
        {logs.length === 0 && (
          <p className="text-slate-600 text-xs text-center mt-8">No events yet.<br/>Trigger an error to see logs.</p>
        )}
        {logs.map(log => (
          <div key={log.id} className="bg-slate-800 rounded px-3 py-2 text-xs border border-slate-700/50">
            <div className="flex items-center justify-between gap-2 mb-1">
              <LogBadge type={log.type} />
              <span className="text-slate-600 font-mono">{log.timestamp}</span>
            </div>
            {log.code && (
              <div className="text-slate-300 font-mono">
                <span className="text-slate-500">code: </span>{log.code}
              </div>
            )}
            {log.action && (
              <div className="text-slate-300 font-mono">
                <span className="text-slate-500">action: </span>
                <span className="text-emerald-400">{log.action}</span>
              </div>
            )}
            {log.reason && (
              <div className="text-slate-400 font-mono truncate">
                <span className="text-slate-500">reason: </span>{log.reason}
              </div>
            )}
            {log.detail && (
              <div className="text-slate-400 truncate">
                <span className="text-slate-500">detail: </span>{log.detail}
              </div>
            )}
          </div>
        ))}
      </div>
      <div className="px-4 py-2 border-t border-slate-700">
        <p className="text-slate-600 text-xs">{logs.length} events (last 50 shown)</p>
      </div>
    </aside>
  )
}

// ---------------------------------------------------------------------------
// Section wrapper
// ---------------------------------------------------------------------------
function Section({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
      {children}
    </div>
  )
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------
const NAV_SECTIONS = [
  { id: 'toast',        label: 'Toast' },
  { id: 'modal',        label: 'Modal' },
  { id: 'inline',       label: 'Inline' },
  { id: 'silent',       label: 'Silent' },
  { id: 'fallback',     label: 'Fallback' },
  { id: 'dedupe',       label: 'Dedupe' },
  { id: 'maxconcurrent',label: 'Max Concurrent' },
  { id: 'transform',    label: 'Transform' },
  { id: 'normalizer',   label: 'Normalizer' },
  { id: 'fetch',        label: 'Fetch' },
  { id: 'boundary',     label: 'Error Boundary' },
  { id: 'callbacks',    label: 'Callbacks' },
  { id: 'debug',        label: 'Debug' },
]

export default function App() {
  const [logs, setLogs] = useState<LogEntry[]>([...lifecycleLogs])

  useEffect(() => {
    const handler = (updated: LogEntry[]) => setLogs(updated)
    logSubscribers.push(handler)
    return () => {
      const idx = logSubscribers.indexOf(handler)
      if (idx !== -1) logSubscribers.splice(idx, 1)
    }
  }, [])

  const scrollTo = (id: string) => {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  return (
    <ErrorEngineProvider engine={engine}>
      <SonnerToaster richColors closeButton />
      <div className="flex min-h-screen bg-slate-50">
        {/* Main content */}
        <div className="flex-1 overflow-y-auto">
          {/* Header */}
          <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
            <div className="max-w-4xl mx-auto px-6 py-4 flex items-center gap-4">
              <div className="w-8 h-8 bg-gradient-to-br from-sky-500 to-blue-600 rounded-lg flex items-center justify-center text-white text-sm font-bold shadow-sm">
                GE
              </div>
              <div>
                <h1 className="text-slate-900 font-bold text-lg leading-none">GracefulErrors</h1>
                <p className="text-slate-500 text-xs mt-0.5">React SDK — Interactive Demo</p>
              </div>
              <nav className="ml-auto flex flex-wrap gap-1">
                {NAV_SECTIONS.map(s => (
                  <button
                    key={s.id}
                    onClick={() => scrollTo(s.id)}
                    className="text-xs text-slate-500 hover:text-sky-600 hover:bg-sky-50 px-2 py-1 rounded transition-colors"
                  >
                    {s.label}
                  </button>
                ))}
              </nav>
            </div>
          </header>

          {/* Sections */}
          <main className="max-w-4xl mx-auto px-6 py-8 space-y-6">
            <Section><div id="toast"><ToastDemo /></div></Section>
            <Section><div id="modal"><ModalDemo /></div></Section>
            <Section><div id="inline"><InlineDemo /></div></Section>
            <Section><div id="silent"><SilentDemo /></div></Section>
            <Section><div id="fallback"><FallbackDemo /></div></Section>
            <Section><div id="dedupe"><DedupeDemo /></div></Section>
            <Section><div id="maxconcurrent"><MaxConcurrentDemo /></div></Section>
            <Section><div id="transform"><TransformDemo /></div></Section>
            <Section><div id="normalizer"><NormalizerDemo /></div></Section>
            <Section><div id="fetch"><FetchDemo /></div></Section>
            <Section><div id="boundary"><BoundaryDemo /></div></Section>
            <Section><div id="callbacks"><CallbacksDemo /></div></Section>
            <Section><div id="debug"><DebugDemo /></div></Section>
          </main>

          <footer className="max-w-4xl mx-auto px-6 py-8 text-center text-slate-400 text-sm border-t border-slate-200 mt-4">
            GracefulErrors React Demo — All features demonstrated with real library API calls
          </footer>
        </div>

        {/* Sidebar log panel */}
        <LogPanel logs={logs} />
      </div>
    </ErrorEngineProvider>
  )
}

// demos/vue/src/App.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import ToastContainer from './components/ToastContainer.vue'
import ModalContainer from './components/ModalContainer.vue'
import EventLog from './components/EventLog.vue'

import ToastDemo from './sections/ToastDemo.vue'
import ModalDemo from './sections/ModalDemo.vue'
import InlineDemo from './sections/InlineDemo.vue'
import SilentDemo from './sections/SilentDemo.vue'
import FallbackDemo from './sections/FallbackDemo.vue'
import DedupeDemo from './sections/DedupeDemo.vue'
import MaxConcurrentDemo from './sections/MaxConcurrentDemo.vue'
import TransformDemo from './sections/TransformDemo.vue'
import NormalizerDemo from './sections/NormalizerDemo.vue'
import FetchDemo from './sections/FetchDemo.vue'
import BoundaryDemo from './sections/BoundaryDemo.vue'
import CallbacksDemo from './sections/CallbacksDemo.vue'
import DebugDemo from './sections/DebugDemo.vue'
import MergeRegistriesDemo from './sections/MergeRegistriesDemo.vue'
import RoutingStrategyDemo from './sections/RoutingStrategyDemo.vue'

type TabId =
  | 'toast' | 'modal' | 'inline' | 'silent' | 'fallback'
  | 'dedupe' | 'concurrent' | 'transform' | 'normalizer'
  | 'fetch' | 'boundary' | 'callbacks' | 'debug'
  | 'merge' | 'routing'

interface Tab {
  id: TabId
  label: string
  badge?: string
  badgeColor?: string
}

const tabs: Tab[] = [
  { id: 'toast', label: 'Toast', badge: 'toast', badgeColor: 'var(--accent-yellow)' },
  { id: 'modal', label: 'Modal', badge: 'modal', badgeColor: 'var(--accent-purple)' },
  { id: 'inline', label: 'Inline', badge: 'inline', badgeColor: 'var(--accent-cyan)' },
  { id: 'silent', label: 'Silent', badge: 'silent', badgeColor: 'var(--text-muted)' },
  { id: 'fallback', label: 'Fallback', badge: 'cfg', badgeColor: 'var(--accent-orange)' },
  { id: 'dedupe', label: 'Dedupe', badge: 'cfg', badgeColor: 'var(--accent-blue)' },
  { id: 'concurrent', label: 'Concurrent', badge: 'cfg', badgeColor: 'var(--accent-pink)' },
  { id: 'transform', label: 'Transform', badge: 'fn', badgeColor: 'var(--accent-green)' },
  { id: 'normalizer', label: 'Normalizer', badge: 'fn', badgeColor: 'var(--accent-cyan)' },
  { id: 'routing', label: 'Routing', badge: 'fn', badgeColor: 'var(--accent-cyan)' },
  { id: 'fetch', label: 'createFetch', badge: 'api', badgeColor: 'var(--accent-blue)' },
  { id: 'merge', label: 'mergeReg', badge: 'api', badgeColor: 'var(--accent-purple)' },
  { id: 'boundary', label: 'Boundary', badge: 'vue', badgeColor: 'var(--accent-green)' },
  { id: 'callbacks', label: 'Callbacks', badge: 'vue', badgeColor: 'var(--accent-green)' },
  { id: 'debug', label: 'Debug', badge: 'cfg', badgeColor: 'var(--accent-orange)' },
]

const activeTab = ref<TabId>('toast')
</script>

<template>
  <div style="display: flex; min-height: 100vh; flex-direction: column;">

    <!-- Header -->
    <header style="
      background: var(--bg-void);
      border-bottom: 1px solid var(--border-dim);
      padding: 0 24px;
      flex-shrink: 0;
      position: sticky;
      top: 0;
      z-index: 100;
    ">
      <div style="display: flex; align-items: center; height: 52px; gap: 20px;">
        <!-- Logo -->
        <div style="display: flex; align-items: center; gap: 10px; flex-shrink: 0;">
          <div style="
            width: 28px; height: 28px;
            background: linear-gradient(135deg, var(--accent-blue), var(--accent-purple));
            border-radius: 6px;
            display: flex; align-items: center; justify-content: center;
            font-size: 14px;
          ">⚡</div>
          <div>
            <div style="font-family: 'Syne', sans-serif; font-weight: 800; font-size: 14px; color: var(--text-white); letter-spacing: -0.02em;">
              gracefulerrors
            </div>
            <div style="font-size: 9px; color: var(--text-muted); letter-spacing: 0.08em; text-transform: uppercase; margin-top: -1px;">
              Vue Demo
            </div>
          </div>
        </div>

        <div style="width: 1px; height: 24px; background: var(--border-dim); flex-shrink: 0;" />

        <!-- Tabs -->
        <div style="display: flex; overflow-x: auto; flex: 1; scrollbar-width: none; -ms-overflow-style: none;">
          <div style="display: flex; gap: 0;">
            <button
              v-for="tab in tabs"
              :key="tab.id"
              class="nav-tab"
              :class="{ active: activeTab === tab.id }"
              @click="activeTab = tab.id"
            >
              {{ tab.label }}
              <span v-if="tab.badge" :style="{
                display: 'inline-block',
                padding: '1px 4px',
                borderRadius: '2px',
                fontSize: '8px',
                fontWeight: '700',
                letterSpacing: '0.06em',
                background: `${tab.badgeColor}18`,
                color: tab.badgeColor,
                marginLeft: '4px',
                border: `1px solid ${tab.badgeColor}28`,
              }">{{ tab.badge }}</span>
            </button>
          </div>
        </div>

        <!-- Version badge -->
        <div style="flex-shrink: 0; font-size: 10px; color: var(--text-muted); font-family: 'JetBrains Mono', monospace;">
          v0.1.2
        </div>
      </div>
    </header>

    <!-- Main layout -->
    <div style="display: flex; flex: 1; overflow: hidden;">

      <!-- Content area -->
      <main style="flex: 1; overflow-y: auto; min-width: 0;">
        <div style="max-width: 900px; margin: 0 auto; padding: 24px 24px 48px;">

          <!-- Section header -->
          <div style="margin-bottom: 20px;">
            <div style="font-size: 10px; color: var(--text-muted); letter-spacing: 0.12em; text-transform: uppercase; margin-bottom: 6px; font-family: 'JetBrains Mono', monospace;">
              gracefulerrors / vue SDK — interactive playground
            </div>
            <div style="height: 1px; background: linear-gradient(90deg, var(--border-mid), transparent);" />
          </div>

          <!-- Active section -->
          <Transition
            name="tab-fade"
            mode="out-in"
          >
            <div :key="activeTab">
              <ToastDemo v-if="activeTab === 'toast'" />
              <ModalDemo v-else-if="activeTab === 'modal'" />
              <InlineDemo v-else-if="activeTab === 'inline'" />
              <SilentDemo v-else-if="activeTab === 'silent'" />
              <FallbackDemo v-else-if="activeTab === 'fallback'" />
              <DedupeDemo v-else-if="activeTab === 'dedupe'" />
              <MaxConcurrentDemo v-else-if="activeTab === 'concurrent'" />
              <TransformDemo v-else-if="activeTab === 'transform'" />
              <NormalizerDemo v-else-if="activeTab === 'normalizer'" />
              <RoutingStrategyDemo v-else-if="activeTab === 'routing'" />
              <FetchDemo v-else-if="activeTab === 'fetch'" />
              <MergeRegistriesDemo v-else-if="activeTab === 'merge'" />
              <BoundaryDemo v-else-if="activeTab === 'boundary'" />
              <CallbacksDemo v-else-if="activeTab === 'callbacks'" />
              <DebugDemo v-else-if="activeTab === 'debug'" />
            </div>
          </Transition>

          <!-- Footer info -->
          <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid var(--border-dim);">
            <div style="display: flex; flex-wrap: wrap; gap: 16px; font-size: 10px; color: var(--text-muted);">
              <span>
                <span style="color: var(--accent-green);">✓</span>
                All features use the real <code style="color: var(--text-dim);">gracefulerrors</code> library
              </span>
              <span>
                <span style="color: var(--accent-blue);">⌘</span>
                Event log tracks all <code style="color: var(--text-dim);">engine.subscribe()</code> events
              </span>
              <span>
                <span style="color: var(--accent-yellow);">⚡</span>
                Renderer is a custom Vue <code style="color: var(--text-dim);">RendererAdapter</code>
              </span>
            </div>
          </div>
        </div>
      </main>

      <!-- Event log sidebar -->
      <EventLog />
    </div>

    <!-- Overlays -->
    <ToastContainer />
    <ModalContainer />
  </div>
</template>

<style>
.tab-fade-enter-active,
.tab-fade-leave-active {
  transition: opacity 0.15s ease, transform 0.15s ease;
}
.tab-fade-enter-from {
  opacity: 0;
  transform: translateY(6px);
}
.tab-fade-leave-to {
  opacity: 0;
  transform: translateY(-4px);
}
</style>
